import express from 'express';
import { OpenAI } from 'openai';
import pdfParse from 'pdf-parse';
import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { getBackendConfig } from '../config';

const router = express.Router();
const config = getBackendConfig();

const openai = new OpenAI({
  apiKey: config.openaiApiKey,
});

// POST /api/review/generate
router.post('/generate', async (req, res) => {
  try {
    const { resumeId, filePath } = req.body;

    if (!resumeId || !filePath) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Read PDF file
    const dataBuffer = fs.readFileSync(filePath);
    const data = await pdfParse(dataBuffer);

    const resumeText = data.text;

    // Generate AI review
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You are an expert resume reviewer. Analyze the provided resume and provide detailed feedback including:
          1. ATS Score (0-100) - How well it will pass Applicant Tracking Systems
          2. Keyword Score (0-100) - Optimization for job descriptions
          3. Grammar Score (0-100) - Language and writing quality
          4. Formatting Score (0-100) - Structure and presentation
          5. Role Fit Score (0-100) - Alignment with target roles
          6. Strengths - What the resume does well
          7. Weaknesses - Areas for improvement
          8. Suggestions - Actionable improvements
          9. Recruiter Perspective - How recruiters view the resume
          
          Return your response as a JSON object with these exact keys.`,
        },
        {
          role: 'user',
          content: resumeText,
        },
      ],
      temperature: 0.7,
    });

    const reviewContent = completion.choices[0].message.content;
    const review = JSON.parse(reviewContent || '{}');

    res.json({
      success: true,
      review,
      resumeId,
    });
  } catch (error) {
    console.error('Review generation error:', error);
    res.status(500).json({ error: 'Failed to generate review' });
  }
});

// GET /api/review/report/:resumeId
router.get('/report/:resumeId', async (req, res) => {
  try {
    const { resumeId } = req.params;

    // Generate PDF report
    const doc = new PDFDocument();
    const chunks: any[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=resume-review-${resumeId}.pdf`);
      res.send(pdfBuffer);
    });

    doc.fontSize(20).text('Resume Review Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Resume ID: ${resumeId}`);
    doc.moveDown();
    doc.fontSize(12).text('Generated by ResumePay AI');
    doc.end();
  } catch (error) {
    console.error('Report generation error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});
  });

  const prompt = `
    Analyze this resume and provide a detailed review in JSON format:
    
    Resume Text:
    ${resumeText}
    
    Return a JSON object with the following structure:
    {
      "atsScore": number (0-100),
      "keywordScore": number (0-100),
      "grammarScore": number (0-100),
      "formattingScore": number (0-100),
      "roleFitScore": number (0-100),
      "overallScore": number (0-100),
      "strengths": string[],
      "weaknesses": string[],
      "suggestions": string[],
      "atsOptimization": string,
      "recruiterPerspective": string
    }
  `;

  const completion = await openai.chat.completions.create({
    model: 'gpt-4-turbo-preview',
    messages: [
      {
        role: 'system',
        content: 'You are an expert resume reviewer and career coach. Analyze resumes and provide detailed, actionable feedback.',
      },
      {
        role: 'user',
        content: prompt,
      },
    ],
    response_format: { type: 'json_object' },
    temperature: 0.7,
  });

  const analysis = JSON.parse(completion.choices[0].message.content || '{}');
  return analysis;
}

async function generatePDFReport(analysis: any, resumeId: string): Promise<string> {
  const reportPath = path.join(uploadDir, `report_${resumeId}.pdf`);
  const doc = new PDFDocument();
  const stream = createWriteStream(reportPath);
  doc.pipe(stream);

  // Title
  doc.fontSize(24).font('Helvetica-Bold').text('Resume Review Report', { align: 'center' });
  doc.moveDown();

  // Overall Score
  doc.fontSize(18).font('Helvetica-Bold').text(`Overall Score: ${analysis.overallScore}/100`);
  doc.moveDown();

  // Score Breakdown
  doc.fontSize(14).font('Helvetica-Bold').text('Score Breakdown:');
  doc.fontSize(12).font('Helvetica');
  doc.text(`ATS Score: ${analysis.atsScore}/100`);
  doc.text(`Keyword Score: ${analysis.keywordScore}/100`);
  doc.text(`Grammar Score: ${analysis.grammarScore}/100`);
  doc.text(`Formatting Score: ${analysis.formattingScore}/100`);
  doc.text(`Role Fit Score: ${analysis.roleFitScore}/100`);
  doc.moveDown();

  // Strengths
  doc.fontSize(14).font('Helvetica-Bold').text('Strengths:');
  doc.fontSize(12).font('Helvetica');
  analysis.strengths.forEach((strength: string) => {
    doc.text(`• ${strength}`);
  });
  doc.moveDown();

  // Weaknesses
  doc.fontSize(14).font('Helvetica-Bold').text('Areas for Improvement:');
  doc.fontSize(12).font('Helvetica');
  analysis.weaknesses.forEach((weakness: string) => {
    doc.text(`• ${weakness}`);
  });
  doc.moveDown();

  // Suggestions
  doc.fontSize(14).font('Helvetica-Bold').text('Suggestions:');
  doc.fontSize(12).font('Helvetica');
  analysis.suggestions.forEach((suggestion: string) => {
    doc.text(`• ${suggestion}`);
  });
  doc.moveDown();

  // ATS Optimization
  doc.fontSize(14).font('Helvetica-Bold').text('ATS Optimization:');
  doc.fontSize(12).font('Helvetica').text(analysis.atsOptimization);
  doc.moveDown();

  // Recruiter Perspective
  doc.fontSize(14).font('Helvetica-Bold').text('Recruiter Perspective:');
  doc.fontSize(12).font('Helvetica').text(analysis.recruiterPerspective);

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(reportPath));
    stream.on('error', reject);
  });
}

export default router;
