import express from 'express';
import { OpenAI } from 'openai';
import pdfParse from 'pdf-parse';
import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { getBackendConfig } from '../config';

const router = express.Router();
const config = getBackendConfig();

const openai = new OpenAI({
  apiKey: config.openaiApiKey,
});

// POST /api/review/generate
router.post('/generate', async (req, res) => {
  try {
    const { resumeId, filePath } = req.body;

    if (!resumeId || !filePath) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Read PDF file
    const dataBuffer = fs.readFileSync(filePath);
    const data = await pdfParse(dataBuffer);

    const resumeText = data.text;

    // Generate AI review
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You are an expert resume reviewer. Analyze the provided resume and provide detailed feedback including:
          1. ATS Score (0-100) - How well it will pass Applicant Tracking Systems
          2. Keyword Score (0-100) - Optimization for job descriptions
          3. Grammar Score (0-100) - Language and writing quality
          4. Formatting Score (0-100) - Structure and presentation
          5. Role Fit Score (0-100) - Alignment with target roles
          6. Strengths - What the resume does well
          7. Weaknesses - Areas for improvement
          8. Suggestions - Actionable improvements
          9. Recruiter Perspective - How recruiters view the resume
          
          Return your response as a JSON object with these exact keys.`,
        },
        {
          role: 'user',
          content: resumeText,
        },
      ],
      temperature: 0.7,
    });

    const reviewContent = completion.choices[0].message.content;
    const review = JSON.parse(reviewContent || '{}');

    res.json({
      success: true,
      review,
      resumeId,
    });
  } catch (error) {
    console.error('Review generation error:', error);
    res.status(500).json({ error: 'Failed to generate review' });
  }
});

// GET /api/review/report/:resumeId
router.get('/report/:resumeId', async (req, res) => {
  try {
    const { resumeId } = req.params;

    // Generate PDF report
    const doc = new PDFDocument();
    const chunks: any[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=resume-review-${resumeId}.pdf`);
      res.send(pdfBuffer);
    });

    doc.fontSize(20).text('Resume Review Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Resume ID: ${resumeId}`);
    doc.moveDown();
    doc.fontSize(12).text('Generated by ResumePay AI');
    doc.end();
  } catch (error) {
    console.error('Report generation error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

export default router;
